Simplification fix
JefersonFG/parser_formais pull request #3
Opened 2018-05-27 01:40 UTC by caiorrs

2018-05-28 14:18 UTC, JefersonFG requested changes
A primeira etapa da remoção de símbolos inúteis está removendo a produção vazia de S. Isso tem a ver com o fato de que V não é uma variável, portanto é tratada como produção inútil, tu precisa checar se as produções geram variáveis ou produções inúteis, mas revisa certinho no livro pra ter certeza

2018-05-28 14:43 UTC, caiorrs commented
acredito que esteja certo agora. Não testei aqui, usei o editor online =P.

2018-05-28 14:49 UTC, JefersonFG commented
And tem preferência no or, agora tu vai inserir na lista qualquer produção que gere o símbolo vazio mesmo que não seja uma produção unitária. E sempre testa antes de postar o código

2018-05-28 14:53 UTC, caiorrs commented
Desculpe, vou ajeitar após almoçar

2018-05-29 13:47 UTC, caiorrs commented
acredito que esteja certo. Eu nao tinha testado o tamanho da producao pois após a remoção de produções vazias, apenas teria S->V

2018-06-14 19:57 UTC, JefersonFG reviewed
Parece bom agora, testei aqui e tudo certo. Só vou te pedir pra remover código comentado e variáveis não utilizadas antes de dar merge.

2018-06-15 00:56 UTC, JefersonFG approved these changes

2018-06-15 00:57 UTC, merged